@todoId = 

### Get all todos
GET http://localhost:6969/todos

### Get a todo by ID
GET http://localhost:6969/todos/{{todoId}}

### Create a new todo
POST http://localhost:6969/todos
Content-Type: application/json  

{
  "title": "New Todo",
  "description": "This is a new todo item."
}

### Try to create a new invalid todo (empty title)
POST http://localhost:6969/todos
Content-Type: application/json  

{
  "title": "",
  "description": "description is ok as long as it's less than 500 characters."
}

### Try to create a new invalid todo (description too long)
POST http://localhost:6969/todos
Content-Type: application/json  

{
  "title": "Any title",
  "description": "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"

}

### Update a todo by ID
PUT http://localhost:6969/todos/{{todoId}}
Content-Type: application/json

{
  "title": "Updated Todo",
  "description": "This is an updated todo item."
}       

### Delete a todo by ID
DELETE http://localhost:6969/todos/{{todoId}}   